package com.yapp.itemfinder.domain.model

enum class CellType {

    EMPTY_CELL,
    CATEGORY_CELL,
    LIKE_CELL,
    SPACE_CELL,
    LOCKER_CELL,
    ADD_LOCKER_CELL,
    HOMETAB_MYSPACE_UPPER_CELL,
    ADD_SPACE_CELL,
    MANAGE_SPACE_CELL,
    ADD_LOCKER_NAME_INPUT_CELL,
    ADD_LOCKER_SPACE_CELL,
    LOCKER_ICONS_CELL,
    ADD_LOCKER_IMAGE_CELL,
    ADD_ITEM_NAME_CELL,
    ADD_ITEM_CATEGORY_CELL,
    ADD_ITEM_LOCATION_CELL,
    ADD_ITEM_COUNT_CELL,
    ADD_ITEM_TAGS_CELL,
    ADD_ITEM_ADDITIONAL_CELL,
    ADD_ITEM_MEMO_CELL,
    ADD_ITEM_EXPIRATION_DATE_CELL,
    ADD_ITEM_PURCHASE_DATE_CELL
}
