package com.yapp.itemfinder.domain.model

enum class CellType {

    EMPTY_CELL,
    CATEGORY_CELL,
    LIKE_CELL,
    SPACE_CELL,
    LOCKER_CELL,
    ADD_LOCKER_CELL,
    HOMETAB_MYSPACE_UPPER_CELL,
    ADD_SPACE_CELL,
    MANAGE_SPACE_CELL,
    ADD_LOCKER_NAME_INPUT_CELL,
    ADD_LOCKER_SPACE_CELL
}
