name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate Keystore file
      run: |
        echo "${{ secrets.FINDTHINGS_KEYSTORE }}" > ../keystore.b64
        base64 -d -i ../keystore.b64 > ../findthings.keystore
    - name: Add keystore Info into local.properties
      run: |
        touch local.properties
        echo -e "\nITEM_FINDER_SIGNING_STORE_PASSWORD=${{ secrets.ITEM_FINDER_SIGNING_STORE_PASSWORD }}" >> local.properties
        echo -e "\nITEM_FINDER_SIGNING_KEY_ALIAS=${{ secrets.ITEM_FINDER_SIGNING_KEY_ALIAS }}" >> local.properties
        echo -e "\nITEM_FINDER_SIGNING_KEY_PASSWORD=${{ secrets.ITEM_FINDER_SIGNING_KEY_PASSWORD }}" >> local.properties
        cat local.properties
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
