name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ITEMFINDER_STORE_PATH: ${{ secrets.ITEMFINDER_STORE_PATH }}
      ITEM_FINDER_SIGNING_STORE_PASSWORD: ${{ secrets.ITEM_FINDER_SIGNING_STORE_PASSWORD }}
      ITEM_FINDER_SIGNING_KEY_ALIAS: ${{ secrets.ITEM_FINDER_SIGNING_KEY_ALIAS }}
      ITEM_FINDER_SIGNING_KEY_PASSWORD: ${{ secrets.ITEM_FINDER_SIGNING_KEY_PASSWORD }}

    steps:
    - name: Add keystore Info into local.properties
      - run: touch local.properties
      - run: echo -e "\nITEMFINDER_STORE_PATH=$ITEMFINDER_STORE_PATH" >> local.properties
      - run: echo -e "\nITEM_FINDER_SIGNING_STORE_PASSWORD=$ITEM_FINDER_SIGNING_STORE_PASSWORD" >> local.properties
      - run: echo -e "\nITEM_FINDER_SIGNING_KEY_ALIAS=$ITEM_FINDER_SIGNING_KEY_ALIAS" >> local.properties
      - run: echo -e "\nITEM_FINDER_SIGNING_KEY_PASSWORD=$ITEM_FINDER_SIGNING_KEY_PASSWORD" >> local.properties
      - run: cat local.properties
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
