- name: Generate Keystore file from Github Secrets
  run: |
    echo "$FINDTHINGS_KEYSTORE" > ./keystore.b64
    base64 -d -i ./keystore.b64 > ./findthings.keystore
  env:
    FINDTHINGS_KEYSTORE: ${{ secrets.FINDTHINGS_KEYSTORE }}
