name: Generate Keystore file from Github Secrets

on:
  pull_request:
    types: [opened]

jobs:
  link_jira_issue: # 작업 이름
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore file
        run: |
          echo "$FINDTHINGS_KEYSTORE" > ./keystore.b64
          base64 -d -i ./keystore.b64 > ./findthings.keystore
        env:
          FINDTHINGS_KEYSTORE: ${{ secrets.FINDTHINGS_KEYSTORE }}
