name: Generate Keystore file from Github Secrets

on:
  pull_request:
    types: [opened]

jobs:
  link_jira_issue: # 작업 이름
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore file
        run: |
          echo "$FINDTHINGS_KEYSTORE" > ./keystore.b64
          base64 -d -i ./keystore.b64 > ./findthings.keystore
        env:
          FINDTHINGS_KEYSTORE: ${{ secrets.FINDTHINGS_KEYSTORE }}
      - name: Add keystore Info into local.properties
        run: |
          touch local.properties
          echo -e "\nITEMFINDER_STORE_PATH=$ITEMFINDER_STORE_PATH" >> local.properties
          echo -e "\nITEM_FINDER_SIGNING_STORE_PASSWORD=$ITEM_FINDER_SIGNING_STORE_PASSWORD" >> local.properties
          echo -e "\nITEM_FINDER_SIGNING_KEY_ALIAS=$ITEM_FINDER_SIGNING_KEY_ALIAS" >> local.properties
          echo -e "\nITEM_FINDER_SIGNING_KEY_PASSWORD=$ITEM_FINDER_SIGNING_KEY_PASSWORD" >> local.properties
          cat local.properties
        env:
          ITEMFINDER_STORE_PATH: ${{ secrets.ITEMFINDER_STORE_PATH }}
          ITEM_FINDER_SIGNING_STORE_PASSWORD: ${{ secrets.ITEM_FINDER_SIGNING_STORE_PASSWORD }}
          ITEM_FINDER_SIGNING_KEY_ALIAS: ${{ secrets.ITEM_FINDER_SIGNING_KEY_ALIAS }}
          ITEM_FINDER_SIGNING_KEY_PASSWORD: ${{ secrets.ITEM_FINDER_SIGNING_KEY_PASSWORD }}
